### ISSUE TITLE
Missing documentation on README

### ISSUE THREAD

**Issue by PDesire** [klst-de/e-invoice#12]
I have a question...

From README.md
`````
  CoreInvoice ublInvoice = new CommercialInvoice(XRECHNUNG_12);
  ublInvoice.setId("123456XX");
  ublInvoice.setIssueDate("2016-04-04");
  ublInvoice.addNote("Es gelten unsere Allgem. Geschäftsbedingungen, die Sie unter […] finden."); // optional
  ublInvoice.setDocumentCurrencyCode(EUR);
  ublInvoice.setOrderReference("1234567890");           // optional
  ublInvoice.setBuyerReference("04011000-12345-34");
...
  CoreInvoiceLine line = new InvoiceLine("1"            // invoice line number
    , new Quantity("XPP", new BigDecimal(1))
    , new Amount(EUR, new BigDecimal(288.79))           // line net amount
    , new UnitPriceAmount(EUR, new BigDecimal(288.79))  // price
    , "Zeitschrift [...]"                               // itemName
    , TaxCategoryCode.StandardRate, new BigDecimal(7)); // VAT category code, rate 7%
    );
  ublInvoice.addLine(line);
...
  transformer.toXML(ublInvoice);
`````

First: this documentation seems like deprecated ? For example ``CommercialInvoice`` is flagged as deprecated.
Second: What does the transformer belong to? What's its Object to be initialized with ? Can you maybe provide a full example ?

Thankyou !

**Comment by homebeaver** [comment]
Tristan @PDesire, tkx for the hint.

_First: this documentation seems like deprecated?_ 
YES, you are right - the README was older then the code. I'll update this.

The java code snippet is similar to the example in `github.com/itplr-kosit` `/xrechnung-testsuite/master/src/test/business-cases/standard/01.01a-INVOICE_ubl.xml`, which is in xml.

_Second: What does the transformer belong to?_
The transformer method `fromModel(ublInvoice)` transforms the java model ublInvoice to xml (marshal). The opposite direction is `toModel(xmlInputStream)` (unmarshal), see https://de.wikipedia.org/wiki/Java_Architecture_for_XML_Binding.

regards EUGen

**Comment by homebeaver** [comment]
I've added a ReadmeTest.
And I close this issue.

**Comment by PDesire** [comment]
Thanks for your explanation and your effort !
